name: Run Spectral on Pull Requests

on:
  - pull_request

  workflow_dispatch:

jobs:
  build:
    name: Run Spectral
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: stoplightio/spectral-action@latest
        with:
          file_glob: 'docs/api/*.yaml'
